version: '3.4'

services:
  sgm.auth.application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - rede_services  

  sgm.cidadao.application:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 8001:80
    depends_on:
      - db
    networks:
      - rede_services        

