version: '3.4'

networks: 
  rede_services:
  rede_gateway:
  rede_web:    

services:
  db:
    container_name: mysql-db-poc
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33060:33060
    env_file:
      - mysql.env
    volumes:
      # Volume dos dados 
      - ./dados:/var/lib/mysql
    networks:
      - rede_services
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  admin_db:
    container_name: mysql-admin-poc
    image: nazarpc/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8082:80
    depends_on:
      - db
    networks:
      - rede_services 
      
  authentication:
    container_name: sgm.auth
    image: vandernunes/sgm.auth
    build:
      context: .
      dockerfile: SGM.Auth/SGM.Auth.Application/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8000:80"
    depends_on:
      - admin_db   
    networks:
     - rede_services
      
  cidadao:
    container_name: sgm.cidadao
    image: vandernunes/sgm.cidadao
    build:
      context: .
      dockerfile: SGM.Cidadao/SGM.Cidadao.Application/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8001:80"
    depends_on:
      - admin_db   
    networks:
      - rede_services
      
  gestao:
    container_name: sgm.gestao
    image: vandernunes/sgm.gestao
    build:
      context: .
      dockerfile: SGM.Gestao/SGM.Gestao.Application/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8002:80"
    depends_on:
      - admin_db   
    networks:
      - rede_services

  web:
    container_name: sgm.web
    image: vandernunes/sgm.web
    build:
      context: .
      dockerfile: SGM.Web/SGM.Web.Application/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - rede_web
      - rede_gateway
      
  gateway:
    container_name: sgm.gateway    
    image: vandernunes/sgm.gateway
    build:
      context: .
      dockerfile: SGM.Gateway/SGM.Gateway.Application/Dockerfile 
    ports:
      - "7000:80"
    depends_on:
      - authentication
      - cidadao
      - gestao
    networks:
      - rede_gateway
      - rede_services
     